# Generated by Django 4.2.7 on 2024-02-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chatmessage_customer_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='customer_chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerchat',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customerchat',
            name='user_customer',
        ),
        migrations.DeleteModel(
            name='AdminMessage',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='CustomerChat',
        ),
    ]
