# Generated by Django 4.2.7 on 2024-02-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
