# Generated by Django 5.0.2 on 2024-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('verified', 'ชำระเงินเรียบร้อย'), ('rejected', 'การชำระเงินถูกปฏิเสธ')], default='pending', max_length=50),
        ),
    ]
